/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

public class SwingProzor extends javax.swing.JFrame {

    /**
     * Creates new form JForm
     */
    public SwingProzor() {
        initComponents();
        dis();
    }
    
    private static void validates(JTextField field) {
    	
    	field.addKeyListener(new java.awt.event.KeyAdapter() {

            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    int number = Integer.parseInt(field.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Only Numbers Allowed");
                    field.setText("");
                }
            }
        });
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        unosRadio = new javax.swing.JRadioButton();
        brisanjeRadio = new javax.swing.JRadioButton();
        izmenaRadio = new javax.swing.JRadioButton();
        prikazSvih_Btn = new javax.swing.JButton();
        pretragaRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unosDohodak = new javax.swing.JTextField();    
        unosAdresa = new javax.swing.JTextField();
        unosGodine = new javax.swing.JTextField();       
        unosIme = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        izmenaIme = new javax.swing.JTextField();
        izmenaGodine = new javax.swing.JTextField();       
        izmenaAdresa = new javax.swing.JTextField();
        izmenaDohodak = new javax.swing.JTextField();   
        jLabel10 = new javax.swing.JLabel();
        brisanjeID = new javax.swing.JTextField(); 
        brisanjeBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pretragaID = new javax.swing.JTextField();
        pretragaBtn = new javax.swing.JButton();
        unesiBtn = new javax.swing.JButton();
        izmeniBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        izmenaTrenutni_ID = new javax.swing.JTextField();       
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        
        validates(unosDohodak);
    	validates(unosGodine);
    	validates(izmenaGodine);
    	validates(pretragaID);
    	validates(izmenaDohodak);
    	validates(brisanjeID);
    	validates(izmenaTrenutni_ID);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setLabelFor(jList1);
        jLabel1.setText("Zaposleni:");
        jLabel1.setToolTipText("");

        buttonGroup1.add(unosRadio);
        unosRadio.setText("Unos zaposlenih");
        unosRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unosRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(brisanjeRadio);
        brisanjeRadio.setText("Obrisi zaposlenog");
        brisanjeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisanjeRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(izmenaRadio);
        izmenaRadio.setText("Izmena podataka zaposlenih");
        izmenaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmenaRadioActionPerformed(evt);
            }
        });

        prikazSvih_Btn.setText("Prikazi sve zaposlene");
        prikazSvih_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikazSvih_BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(pretragaRadio);
        pretragaRadio.setText("Pretraga zaposlenih");
        pretragaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretragaRadioActionPerformed(evt);
            }
        });

        jLabel2.setLabelFor(unosIme);
        jLabel2.setText("Ime: ");

        jLabel3.setLabelFor(unosGodine);
        jLabel3.setText("Br. godina: ");

        jLabel4.setLabelFor(unosAdresa);
        jLabel4.setText("Adresa: ");

        jLabel5.setLabelFor(unosDohodak);
        jLabel5.setText("Dohodak: ");

        jLabel6.setLabelFor(izmenaIme);
        jLabel6.setText("Novo ime: ");

        jLabel7.setLabelFor(izmenaGodine);
        jLabel7.setText("Novi br. godina: ");

        jLabel8.setLabelFor(izmenaAdresa);
        jLabel8.setText("Nova adresa: ");

        jLabel9.setLabelFor(izmenaDohodak);
        jLabel9.setText("Novi dohodak: ");

        jLabel10.setLabelFor(brisanjeID);
        jLabel10.setText("ID zaposlenog: ");

        brisanjeBtn.setText("Ukloni zaposlenog");
        brisanjeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brisanjeBtnActionPerformed(evt);
            }
        });

        jLabel11.setLabelFor(pretragaID);
        jLabel11.setText("ID zaposlenog: ");

        pretragaBtn.setText("Pretrazi");
        pretragaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretragaBtnActionPerformed(evt);
            }
        });

        unesiBtn.setText("Unesi");
        unesiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unesiBtnActionPerformed(evt);
            }
        });

        izmeniBtn.setText("Izmeni");
        izmeniBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmeniBtnActionPerformed(evt);
            }
        });

        jLabel14.setLabelFor(izmenaTrenutni_ID);
        jLabel14.setText("Trenutni ID:");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brisanjeID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(brisanjeBtn)
                    .addComponent(unesiBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(unosDohodak, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unosRadio)
                                    .addComponent(brisanjeRadio))
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unosIme, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unosGodine, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(unosAdresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pretragaRadio)
                            .addComponent(izmenaRadio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(izmenaIme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(izmenaGodine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(izmenaTrenutni_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(izmeniBtn)
                                    .addComponent(jLabel8))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(izmenaAdresa)
                                    .addComponent(izmenaDohodak))))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(pretragaID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pretragaBtn)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prikazSvih_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unosRadio)
                            .addComponent(izmenaRadio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(izmenaTrenutni_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(unosIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(izmenaIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(unosGodine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(izmenaGodine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(unosAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(izmenaAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(unosDohodak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(izmenaDohodak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(izmeniBtn)
                            .addComponent(unesiBtn))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brisanjeRadio)
                            .addComponent(pretragaRadio))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(brisanjeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(pretragaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pretragaBtn)
                            .addComponent(brisanjeBtn)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prikazSvih_Btn)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dis() {
        izmeniBtn.setEnabled(false);
        izmenaAdresa.setEnabled(false);
        izmenaDohodak.setEnabled(false);
        izmenaGodine.setEnabled(false);
        izmenaIme.setEnabled(false);
        izmenaTrenutni_ID.setEnabled(false);
        brisanjeBtn.setEnabled(false);
        brisanjeID.setEnabled(false);
        pretragaBtn.setEnabled(false);
        pretragaID.setEnabled(false);
        unesiBtn.setEnabled(false);
        unosAdresa.setEnabled(false);
        unosDohodak.setEnabled(false);
        unosGodine.setEnabled(false);
        unosIme.setEnabled(false);

    }

    private void unosRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unosRadioActionPerformed
        if (unosRadio.isSelected()) {

            izmeniBtn.setEnabled(false);
            izmenaAdresa.setEnabled(false);
            izmenaAdresa.setText("");
            izmenaDohodak.setEnabled(false);
            izmenaDohodak.setText("");
            izmenaGodine.setEnabled(false);
            izmenaGodine.setText("");
            izmenaIme.setEnabled(false);
            izmenaIme.setText("");
            izmenaTrenutni_ID.setEnabled(false);
            izmenaTrenutni_ID.setText("");
            brisanjeBtn.setEnabled(false);
            brisanjeID.setEnabled(false);
            brisanjeID.setText("");
            pretragaBtn.setEnabled(false);
            pretragaID.setEnabled(false);
            pretragaID.setText("");

            unesiBtn.setEnabled(true);
            unosAdresa.setEnabled(true);
            unosDohodak.setEnabled(true);
            unosGodine.setEnabled(true);
            unosIme.setEnabled(true);

        }
    }//GEN-LAST:event_unosRadioActionPerformed

    private void izmenaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmenaRadioActionPerformed
        if (izmenaRadio.isSelected()) {

            brisanjeBtn.setEnabled(false);
            brisanjeID.setEnabled(false);
            brisanjeID.setText("");
            pretragaBtn.setEnabled(false);
            pretragaID.setEnabled(false);
            pretragaID.setText("");
            unesiBtn.setEnabled(false);
            unosAdresa.setEnabled(false);
            unosAdresa.setText("");
            unosDohodak.setEnabled(false);
            unosDohodak.setText("");
            unosGodine.setEnabled(false);
            unosGodine.setText("");
            unosIme.setEnabled(false);
            unosIme.setText("");

            izmeniBtn.setEnabled(true);
            izmenaAdresa.setEnabled(true);
            izmenaDohodak.setEnabled(true);
            izmenaGodine.setEnabled(true);
            izmenaIme.setEnabled(true);
            izmenaTrenutni_ID.setEnabled(true);
        }
    }//GEN-LAST:event_izmenaRadioActionPerformed

    private void brisanjeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisanjeRadioActionPerformed
        if (brisanjeRadio.isSelected()) {

            pretragaBtn.setEnabled(false);
            pretragaID.setEnabled(false);
            pretragaID.setText("");
            unesiBtn.setEnabled(false);
            unosAdresa.setEnabled(false);
            unosAdresa.setText("");
            unosDohodak.setEnabled(false);
            unosDohodak.setText("");
            unosGodine.setEnabled(false);
            unosGodine.setText("");
            unosIme.setEnabled(false);
            unosIme.setText("");
            izmeniBtn.setEnabled(false);
            izmenaAdresa.setEnabled(false);
            izmenaAdresa.setText("");
            izmenaDohodak.setEnabled(false);
            izmenaDohodak.setText("");
            izmenaGodine.setEnabled(false);
            izmenaGodine.setText("");
            izmenaIme.setEnabled(false);
            izmenaIme.setText("");
            izmenaTrenutni_ID.setEnabled(false);
            izmenaTrenutni_ID.setText("");

            brisanjeBtn.setEnabled(true);
            brisanjeID.setEnabled(true);
        }
    }//GEN-LAST:event_brisanjeRadioActionPerformed

    private void pretragaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretragaRadioActionPerformed
        if (pretragaRadio.isSelected()) {

            unesiBtn.setEnabled(false);
            unosAdresa.setEnabled(false);
            unosAdresa.setText("");
            unosDohodak.setEnabled(false);
            unosDohodak.setText("");
            unosGodine.setEnabled(false);
            unosGodine.setText("");
            unosIme.setEnabled(false);
            unosIme.setText("");
            izmeniBtn.setEnabled(false);
            izmenaAdresa.setEnabled(false);
            izmenaAdresa.setText("");
            izmenaDohodak.setEnabled(false);
            izmenaDohodak.setText("");
            izmenaGodine.setEnabled(false);
            izmenaGodine.setText("");
            izmenaIme.setEnabled(false);
            izmenaIme.setText("");
            izmenaTrenutni_ID.setEnabled(false);
            izmenaTrenutni_ID.setText("");
            brisanjeBtn.setEnabled(false);
            brisanjeID.setEnabled(false);
            brisanjeID.setText("");

            pretragaBtn.setEnabled(true);
            pretragaID.setEnabled(true);
        }
    }//GEN-LAST:event_pretragaRadioActionPerformed


    private void unesiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unesiBtnActionPerformed
        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        try {

            tx = session.beginTransaction();

            Radnik radnik = new Radnik(unosIme.getText(), Integer.valueOf(unosGodine.getText()), Integer.valueOf(unosDohodak.getText()), unosAdresa.getText());

            session.persist(radnik);
            //  JOptionPane.showMessageDialog(new JFrame(), "Unos podataka o zaposlenom je uspesno obavljen!");

            tx.commit();

        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }
    }//GEN-LAST:event_unesiBtnActionPerformed

    private void izmeniBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmeniBtnActionPerformed
        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        try {

            tx = session.beginTransaction();

            Radnik radnik = (Radnik) session.load(Radnik.class, Integer.valueOf(izmenaTrenutni_ID.getText()));

            radnik.setAdresa(izmenaAdresa.getText());
            radnik.setGodine(Integer.valueOf(izmenaGodine.getText()));
            radnik.setDohodak(Integer.valueOf(izmenaIme.getText()));
            radnik.setIme(izmenaIme.getText());

            session.merge(radnik);

            tx.commit();
        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        }
    }//GEN-LAST:event_izmeniBtnActionPerformed

    private void brisanjeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brisanjeBtnActionPerformed
        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();

            Radnik radnik = (Radnik) session.get(Radnik.class, Integer.valueOf(brisanjeID.getText()));
            session.delete(radnik);

            tx.commit();
        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        } finally {
            HibernateUtil.close();
        }
    }//GEN-LAST:event_brisanjeBtnActionPerformed

    private void pretragaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretragaBtnActionPerformed
        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();

            Radnik radnik = (Radnik) session.get(Radnik.class, Integer.valueOf(pretragaID.getText()));

            DefaultListModel listModel = new DefaultListModel();

            listModel.addElement(radnik);

            jList1.setModel(listModel);

            tx.commit();
        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        } finally {
            HibernateUtil.close();
        }
    }//GEN-LAST:event_pretragaBtnActionPerformed

    private void prikazSvih_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikazSvih_BtnActionPerformed
        Session session = HibernateUtil.createSessionFactory().openSession();
        Transaction tx = null;

        try {
            tx = session.beginTransaction();

            // Radnik radnik = null;
            List<Radnik> list = new ArrayList();

            String hql = "from Radnik";

            Query query = session.createQuery(hql);

            list = query.list();

            DefaultListModel listModel = new DefaultListModel();

            for (int i = 0; i < list.size(); i++) {
                listModel.addElement(list.get(i));
            }
            jList1.setModel(listModel);

            tx.commit();
        } catch (HibernateException e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e);
        } finally {
            HibernateUtil.close();
        }
    }//GEN-LAST:event_prikazSvih_BtnActionPerformed

    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingProzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton brisanjeBtn;
    public static javax.swing.JTextField brisanjeID;
    private javax.swing.JRadioButton brisanjeRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField izmenaAdresa;
    public static javax.swing.JTextField izmenaDohodak;
    public static javax.swing.JTextField izmenaGodine;
    public static javax.swing.JTextField izmenaIme;
    private javax.swing.JRadioButton izmenaRadio;
    public static javax.swing.JTextField izmenaTrenutni_ID;
    public static javax.swing.JButton izmeniBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton pretragaBtn;
    public static javax.swing.JTextField pretragaID;
    private javax.swing.JRadioButton pretragaRadio;
    public static javax.swing.JButton prikazSvih_Btn;
    public static javax.swing.JButton unesiBtn;
    public static javax.swing.JTextField unosAdresa;
    public static javax.swing.JTextField unosDohodak;
    public static javax.swing.JTextField unosGodine;
    public static javax.swing.JTextField unosIme;
    private javax.swing.JRadioButton unosRadio;
    // End of variables declaration//GEN-END:variables
}
